language: php
php:
  - 5.3
  - 5.4
before_script:
  - wget http://softlayer.dl.sourceforge.net/project/simpletest/simpletest/simpletest_1.1/simpletest_1.1.0.tar.gz
  - tar xf simpletest_1.1.0.tar.gz
script: "php test/Stripe.php"
